# This file has been generated by node2nix 1.11.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@ts-morph/common-0.9.2" = {
      name = "_at_ts-morph_slash_common";
      packageName = "@ts-morph/common";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ts-morph/common/-/common-0.9.2.tgz";
        sha512 = "IPyg+c3Am0EBoa63W0f/AKeLrJhvzMzQ4BIvD1baxLopmiHOj1HFTXYxC6e8iTZ+UYtN+/WFM9UyGRnoA20b8g==";
      };
    };
    "@types/connect-3.4.35" = {
      name = "_at_types_slash_connect";
      packageName = "@types/connect";
      version = "3.4.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/connect/-/connect-3.4.35.tgz";
        sha512 = "cdeYyv4KWoEgpBISTxWvqYsVy444DOqehiF3fM3ne10AmJ62RSyNkUnxMJXHQWRQQX2eR94m5y1IZyDwBjV9FQ==";
      };
    };
    "@types/express-serve-static-core-4.17.28" = {
      name = "_at_types_slash_express-serve-static-core";
      packageName = "@types/express-serve-static-core";
      version = "4.17.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/express-serve-static-core/-/express-serve-static-core-4.17.28.tgz";
        sha512 = "P1BJAEAW3E2DJUlkgq4tOL3RyMunoWXqbSCygWo5ZIWTjUgN1YnaXWW4VWl/oc8vs/XoYibEGBKP0uZyF4AHig==";
      };
    };
    "@types/lodash-4.14.180" = {
      name = "_at_types_slash_lodash";
      packageName = "@types/lodash";
      version = "4.14.180";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/lodash/-/lodash-4.14.180.tgz";
        sha512 = "XOKXa1KIxtNXgASAnwj7cnttJxS4fksBRywK/9LzRV5YxrF80BXZIGeQSuoESQ/VkUj30Ae0+YcuHc15wJCB2g==";
      };
    };
    "@types/node-10.12.18" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "10.12.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-10.12.18.tgz";
        sha512 = "fh+pAqt4xRzPfqA6eh3Z2y6fyZavRIumvjhaCL753+TVkGKGhpPeyrJG2JftD0T9q4GF00KjefsQ+PQNDdWQaQ==";
      };
    };
    "@types/node-11.11.6" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "11.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-11.11.6.tgz";
        sha512 = "Exw4yUWMBXM3X+8oqzJNRqZSwUAaS4+7NdvHqQuFi/d+synz++xmX3QIf+BFqneW8N31R8Ky+sikfZUXq07ggQ==";
      };
    };
    "@types/node-12.20.47" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "12.20.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-12.20.47.tgz";
        sha512 = "BzcaRsnFuznzOItW1WpQrDHM7plAa7GIDMZ6b5pnMbkqEtM/6WCOhvZar39oeMQP79gwvFUWjjptE7/KGcNqFg==";
      };
    };
    "@types/qs-6.9.7" = {
      name = "_at_types_slash_qs";
      packageName = "@types/qs";
      version = "6.9.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/qs/-/qs-6.9.7.tgz";
        sha512 = "FGa1F62FT09qcrueBA6qYTrJPVDzah9a+493+o2PCXsesWHIn27G98TsSMs3WPNbZIEj4+VJf6saSFpvD+3Zsw==";
      };
    };
    "@types/range-parser-1.2.4" = {
      name = "_at_types_slash_range-parser";
      packageName = "@types/range-parser";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/range-parser/-/range-parser-1.2.4.tgz";
        sha512 = "EEhsLsD6UsDM1yFhAvy0Cjr6VwmpMWqFBCb9w07wVugF7w9nfajxLuVmngTIpgS6svCnm6Vaw+MZhoDCKnOfsw==";
      };
    };
    "@types/ws-7.4.7" = {
      name = "_at_types_slash_ws";
      packageName = "@types/ws";
      version = "7.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ws/-/ws-7.4.7.tgz";
        sha512 = "JQbbmxZTZehdc2iszGKs5oC3NFnjeay7mtAWrdt7qNtAVK0g19muApzAy4bm9byz79xa2ZnO/BOBC2R8RC5Lww==";
      };
    };
    "@webassemblyjs/ast-1.11.1" = {
      name = "_at_webassemblyjs_slash_ast";
      packageName = "@webassemblyjs/ast";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/ast/-/ast-1.11.1.tgz";
        sha512 = "ukBh14qFLjxTQNTXocdyksN5QdM28S1CxHt2rdskFyL+xFV7VremuBLVbmCePj+URalXBENx/9Lm7lnhihtCSw==";
      };
    };
    "@webassemblyjs/floating-point-hex-parser-1.11.1" = {
      name = "_at_webassemblyjs_slash_floating-point-hex-parser";
      packageName = "@webassemblyjs/floating-point-hex-parser";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/floating-point-hex-parser/-/floating-point-hex-parser-1.11.1.tgz";
        sha512 = "iGRfyc5Bq+NnNuX8b5hwBrRjzf0ocrJPI6GWFodBFzmFnyvrQ83SHKhmilCU/8Jv67i4GJZBMhEzltxzcNagtQ==";
      };
    };
    "@webassemblyjs/helper-api-error-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-api-error";
      packageName = "@webassemblyjs/helper-api-error";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-api-error/-/helper-api-error-1.11.1.tgz";
        sha512 = "RlhS8CBCXfRUR/cwo2ho9bkheSXG0+NwooXcc3PAILALf2QLdFyj7KGsKRbVc95hZnhnERon4kW/D3SZpp6Tcg==";
      };
    };
    "@webassemblyjs/helper-numbers-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-numbers";
      packageName = "@webassemblyjs/helper-numbers";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-numbers/-/helper-numbers-1.11.1.tgz";
        sha512 = "vDkbxiB8zfnPdNK9Rajcey5C0w+QJugEglN0of+kmO8l7lDb77AnlKYQF7aarZuCrv+l0UvqL+68gSDr3k9LPQ==";
      };
    };
    "@webassemblyjs/helper-wasm-bytecode-1.11.1" = {
      name = "_at_webassemblyjs_slash_helper-wasm-bytecode";
      packageName = "@webassemblyjs/helper-wasm-bytecode";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webassemblyjs/helper-wasm-bytecode/-/helper-wasm-bytecode-1.11.1.tgz";
        sha512 = "PvpoOGiJwXeTrSf/qfudJhwlvDQxFgelbMqtq52WWiXC6Xgg1IREdngmPN3bs4RoO83PnL/nFrxucXj1+BX62Q==";
      };
    };
    "@xtuc/long-4.2.2" = {
      name = "_at_xtuc_slash_long";
      packageName = "@xtuc/long";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xtuc/long/-/long-4.2.2.tgz";
        sha512 = "NuHqBY1PB/D8xU6s/thBgOAiAP7HOYDQ32+BFZILJ8ivkUkAHQnWfn6WhL79Owj1qmUnoN/YPhktdIoucipkAQ==";
      };
    };
    "JSONStream-1.3.5" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz";
        sha512 = "E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ==";
      };
    };
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "abstract-leveldown-7.2.0" = {
      name = "abstract-leveldown";
      packageName = "abstract-leveldown";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abstract-leveldown/-/abstract-leveldown-7.2.0.tgz";
        sha512 = "DnhQwcFEaYsvYDnACLZhMmCWd3rkOeEvglpa4q5i/5Jlm3UIsWaxVzuXvDLFCSCWRO3yy2/+V/G7FusFgejnfQ==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "arbitrary-1.4.10" = {
      name = "arbitrary";
      packageName = "arbitrary";
      version = "1.4.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/arbitrary/-/arbitrary-1.4.10.tgz";
        sha512 = "YU4rMv5yk9GS/1e8pWgrhnWfnE3SaTnS17fcX2VEY2stilqL5++SI4nPAyF5RZkY2DWRkXy/i+Opl8XHBNvNSA==";
      };
    };
    "asn1-0.2.6" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.6.tgz";
        sha512 = "ix/FxPn0MDjeyJ7i/yoHGFt/EX6LyNbxSEhPPXODPL+KB0VPk86UYfL0lMdy+KCnv+fmvIzySwaK5COwqVbWTQ==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-2.6.3" = {
      name = "async";
      packageName = "async";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.3.tgz";
        sha512 = "zflvls11DCy+dQWzTW2dzuilv8Z5X/pjfmZOWba6TNIVDm+2UDaJmXSOXlasHKfNBs8oo3M0aT50fDEWfKZjXg==";
      };
    };
    "async-3.2.3" = {
      name = "async";
      packageName = "async";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-3.2.3.tgz";
        sha512 = "spZRyzKL5l5BZQrr/6m/SqFdBN0q3OCI0f9rjfBzCMBIP4p75P620rR3gTmaksNOhmzgdxcaxdNfMy6anrbM0g==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.11.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.11.0.tgz";
        sha512 = "xh1Rl34h6Fi1DC2WWKfxUTVqRsNnr6LsKz2+hfwDxQJWmrx8+c7ylaqBMcHfl1U1r2dsifOvKX3LQuLNZ+XSvA==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base-x-1.1.0" = {
      name = "base-x";
      packageName = "base-x";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base-x/-/base-x-1.1.0.tgz";
        sha1 = "42d3d717474f9ea02207f6d1aa1f426913eeb7ac";
      };
    };
    "base-x-3.0.9" = {
      name = "base-x";
      packageName = "base-x";
      version = "3.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/base-x/-/base-x-3.0.9.tgz";
        sha512 = "H7JU6iBHTal1gp56aKoaa//YUxEaAOUiydvrV/pILqIHXTtqxSkATOnDA2u+jZ/61sD+L/412+7kzXRtWukhpQ==";
      };
    };
    "base58check-2.0.0" = {
      name = "base58check";
      packageName = "base58check";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base58check/-/base58check-2.0.0.tgz";
        sha1 = "8046652d14bc87f063bd16be94a39134d3b61173";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bcoin-git+https://github.com/bcoin-org/bcoin#acdeb84767f3ceb82b4a75931fe353229c3bc7b5" = {
      name = "bcoin";
      packageName = "bcoin";
      version = "2.2.0";
      src = fetchgit {
        url = "https://github.com/bcoin-org/bcoin";
        rev = "acdeb84767f3ceb82b4a75931fe353229c3bc7b5";
        sha256 = "aa7c55c0d755bf1842f60648bd4a984a3dd0db9549133251281a9c4a888386ab";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "bech32-2.0.0" = {
      name = "bech32";
      packageName = "bech32";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bech32/-/bech32-2.0.0.tgz";
        sha512 = "LcknSilhIGatDAsY1ak2I8VtGaHNhgMSYVxFrGLXv+xLHytaKZKcaUJJUE7qmBr7h33o5YQwP55pMI0xmkpJwg==";
      };
    };
    "bigi-1.4.2" = {
      name = "bigi";
      packageName = "bigi";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bigi/-/bigi-1.4.2.tgz";
        sha1 = "9c665a95f88b8b08fc05cfd731f561859d725825";
      };
    };
    "bip-schnorr-0.6.6" = {
      name = "bip-schnorr";
      packageName = "bip-schnorr";
      version = "0.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip-schnorr/-/bip-schnorr-0.6.6.tgz";
        sha512 = "QZmVN37kaKfEk6M61gfcREa5JxWVQ0LvA95UQQD5mdyZsN6542PwfrvlAARZufTLn2ZIQQ0ph6XHD0vq8J3ouw==";
      };
    };
    "bip174-2.0.1" = {
      name = "bip174";
      packageName = "bip174";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip174/-/bip174-2.0.1.tgz";
        sha512 = "i3X26uKJOkDTAalYAp0Er+qGMDhrbbh2o93/xiPyAN2s25KrClSpe3VXo/7mNJoqA5qfko8rLS2l3RWZgYmjKQ==";
      };
    };
    "bip32-3.0.1" = {
      name = "bip32";
      packageName = "bip32";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip32/-/bip32-3.0.1.tgz";
        sha512 = "Uhpp9aEx3iyiO7CpbNGFxv9WcMIVdGoHG04doQ5Ln0u60uwDah7jUSc3QMV/fSZGm/Oo01/OeAmYevXV+Gz5jQ==";
      };
    };
    "bip39-3.0.4" = {
      name = "bip39";
      packageName = "bip39";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip39/-/bip39-3.0.4.tgz";
        sha512 = "YZKQlb752TrUWqHWj7XAwCSjYEgGAk+/Aas3V7NyjQeZYsztO8JnQUaCWhcnL4T+jL8nvB8typ2jRPzTlgugNw==";
      };
    };
    "bip65-1.0.3" = {
      name = "bip65";
      packageName = "bip65";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip65/-/bip65-1.0.3.tgz";
        sha512 = "RQ1nc7xtnLa5XltnCqkoR2zmhuz498RjMJwrLKQzOE049D1HUqnYfon7cVSbwS5UGm0/EQlC2CH+NY3MyITA4Q==";
      };
    };
    "bip68-1.0.4" = {
      name = "bip68";
      packageName = "bip68";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip68/-/bip68-1.0.4.tgz";
        sha512 = "O1htyufFTYy3EO0JkHg2CLykdXEtV2ssqw47Gq9A0WByp662xpJnMEB9m43LZjsSDjIAOozWRExlFQk2hlV1XQ==";
      };
    };
    "bitcoinjs-lib-6.0.1" = {
      name = "bitcoinjs-lib";
      packageName = "bitcoinjs-lib";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bitcoinjs-lib/-/bitcoinjs-lib-6.0.1.tgz";
        sha512 = "x/7D4jDj/MMkmO6t3p2CSDXTqpwZ/jRsRiJDmaiXabrR9XRo7jwby8HRn7EyK1h24rKFFI7vI0ay4czl6bDOZQ==";
      };
    };
    "blessed-0.1.81" = {
      name = "blessed";
      packageName = "blessed";
      version = "0.1.81";
      src = fetchurl {
        url = "https://registry.npmjs.org/blessed/-/blessed-0.1.81.tgz";
        sha1 = "f962d687ec2c369570ae71af843256e6d0ca1129";
      };
    };
    "bn.js-4.12.0" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.12.0.tgz";
        sha512 = "c98Bf3tPniI+scsdk237ku1Dc3ujXQTSgyiPUDEOe7tRkhrqridvh8klBv0HCEso1OLOYcHuCv/cS6DNxKH+ZA==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "bs58-3.1.0" = {
      name = "bs58";
      packageName = "bs58";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58/-/bs58-3.1.0.tgz";
        sha1 = "d4c26388bf4804cac714141b1945aa47e5eb248e";
      };
    };
    "bs58-4.0.1" = {
      name = "bs58";
      packageName = "bs58";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58/-/bs58-4.0.1.tgz";
        sha1 = "be161e76c354f6f788ae4071f63f34e8c4f0a42a";
      };
    };
    "bs58check-2.1.2" = {
      name = "bs58check";
      packageName = "bs58check";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58check/-/bs58check-2.1.2.tgz";
        sha512 = "0TS1jicxdU09dwJMNZtVAfzPi6Q6QeN0pM1Fkzrjn+XYHvzMKPU3pHVpva+769iNVSfIYWf7LJ6WR+BuuMf8cA==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "buffer-reverse-1.0.1" = {
      name = "buffer-reverse";
      packageName = "buffer-reverse";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-reverse/-/buffer-reverse-1.0.1.tgz";
        sha1 = "49283c8efa6f901bc01fa3304d06027971ae2f60";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "catering-2.1.1" = {
      name = "catering";
      packageName = "catering";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/catering/-/catering-2.1.1.tgz";
        sha512 = "K7Qy8O9p76sL3/3m7/zLKbRkyOlSZAgzEaLhyj2mXS8PsCud2Eo4hAb8aLtZqHh0QGqLcb9dlJSu6lHRVENm1w==";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "clightningjs-0.2.2" = {
      name = "clightningjs";
      packageName = "clightningjs";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clightningjs/-/clightningjs-0.2.2.tgz";
        sha512 = "9fdWYNxe/IUe0uG0b1XdxWGlev1IPlWZpN6Hrsr3uTOZe1kSR+ySBMzdsgD73Rc3LeX7DfdKhT3uuT8B77HIqg==";
      };
    };
    "code-block-writer-10.1.1" = {
      name = "code-block-writer";
      packageName = "code-block-writer";
      version = "10.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-block-writer/-/code-block-writer-10.1.1.tgz";
        sha512 = "67ueh2IRGst/51p0n6FvPrnRjAGHY5F8xdjkgrYE7DDzpJe6qA07RYQ9VcoUeo5ATOjSOiWpSL3SWBRRbempMw==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-6.2.1" = {
      name = "commander";
      packageName = "commander";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-6.2.1.tgz";
        sha512 = "U7VdrJFnJgo4xjrHpTzu0yrHPGImdsmD95ZlgYSEajAn2JKzDhDTPG9kBTefmObL2w/ngeZnilk+OV9CG3d7UA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "config-chain-1.1.13" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.13.tgz";
        sha512 = "qj+f8APARXHrM0hraqXYb2/bOVSV4PvJQlNZ/DVj0QrmNM2q2euizkeuVckQ57J+W0mRH6Hvi+k50M4Jul2VRQ==";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 = "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "crypto-js-3.3.0" = {
      name = "crypto-js";
      packageName = "crypto-js";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-js/-/crypto-js-3.3.0.tgz";
        sha512 = "DIT51nX0dCfKltpRiXV+/TVZq+Qq2NgF4644+K7Ttnla7zEzqc+kjJyiB96BHNyUTBxyjzRcZYpUdZa+QAqi6Q==";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "deferred-leveldown-7.0.0" = {
      name = "deferred-leveldown";
      packageName = "deferred-leveldown";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deferred-leveldown/-/deferred-leveldown-7.0.0.tgz";
        sha512 = "QKN8NtuS3BC6m0B8vAnBls44tX1WXAFATUsJlruyAYbZpysWV3siH6o/i3g9DCHauzodksO60bdj5NazNbjCmg==";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "delay-5.0.0" = {
      name = "delay";
      packageName = "delay";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delay/-/delay-5.0.0.tgz";
        sha512 = "ReEBKkIfe4ya47wlPYf/gu5ib6yUG0/Aez0JQZQz94kiWtRQvZIQbTiehsnwHvLSWJnQdhVeqYue7Id1dKr0qw==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "denque-1.5.1" = {
      name = "denque";
      packageName = "denque";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/denque/-/denque-1.5.1.tgz";
        sha512 = "XwE+iZ4D6ZUB7mfYRMb5wByE8L74HCn30FBN7sWnXksWc1LO1bPDl67pBR9o/kC4z/xSNAwkMYcGgqDV3BE3Hw==";
      };
    };
    "dotparser-0.3.0" = {
      name = "dotparser";
      packageName = "dotparser";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dotparser/-/dotparser-0.3.0.tgz";
        sha512 = "TfIlRRKpYFu/KwJq/dm+BWqb4KtwTO1XIwWMaElu/EF3s+r1FRNGIS2bzK0uuAQ+dd3TlJKaoSiHp8Y09Q0ZZA==";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "ecpair-2.0.1" = {
      name = "ecpair";
      packageName = "ecpair";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecpair/-/ecpair-2.0.1.tgz";
        sha512 = "iT3wztQMeE/nDTlfnAg8dAFUfBS7Tq2BXzq3ae6L+pWgFU0fQ3l0woTzdTBrJV3OxBjxbzjq8EQhAbEmJNWFSw==";
      };
    };
    "ecurve-1.0.6" = {
      name = "ecurve";
      packageName = "ecurve";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecurve/-/ecurve-1.0.6.tgz";
        sha512 = "/BzEjNfiSuB7jIWKcS/z8FK9jNjmEWvUV2YZ4RLSmcDtP7Lq0m6FvDuSnJpBlDpGRpfRQeTLGLBI8H+kEv0r+w==";
      };
    };
    "editorconfig-0.15.3" = {
      name = "editorconfig";
      packageName = "editorconfig";
      version = "0.15.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/editorconfig/-/editorconfig-0.15.3.tgz";
        sha512 = "M9wIMFx96vq0R4F+gRpY3o2exzb8hEj/n9S8unZtHSvYjibBp/iMufSzvmOcV/laG0ZtuTVGtiJggPOSW2r93g==";
      };
    };
    "elliptic-6.5.4" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.5.4.tgz";
        sha512 = "iLhC6ULemrljPZb+QutR5TQGB+pdW6KGD5RSegS+8sorOZT+rdQFbsQFJgvN3eRqNALqJer4oQ16YvJHlU8hzQ==";
      };
    };
    "encoding-down-7.1.0" = {
      name = "encoding-down";
      packageName = "encoding-down";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding-down/-/encoding-down-7.1.0.tgz";
        sha512 = "ky47X5jP84ryk5EQmvedQzELwVJPjCgXDQZGeb9F6r4PdChByCGHTBrVcF3h8ynKVJ1wVbkxTsDC8zBROPypgQ==";
      };
    };
    "es6-promise-4.2.8" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-4.2.8.tgz";
        sha512 = "HJDGx5daxeIvxdBxvG2cb9g4tEvwIk3i8+nhX0yGrYmZUzbkdg8QbDevheDB8gd0//uPj4c1EQua8Q+MViT0/w==";
      };
    };
    "es6-promisify-5.0.0" = {
      name = "es6-promisify";
      packageName = "es6-promisify";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promisify/-/es6-promisify-5.0.0.tgz";
        sha1 = "5109d62f3e56ea967c4b63505aef08291c8a5203";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "fast-deep-equal-2.0.1" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-2.0.1.tgz";
        sha1 = "7b05218ddf9667bf7f370bf7fdb2cb15fdd0aa49";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-glob-3.2.11" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.2.11.tgz";
        sha512 = "xrO3+1bxSo3ZVHAnqzyuewYT6aMFHRAd4Kcs92MAonjwQZLsK9d0SF1IyQ3k5PoirxTW0Oe/RqFgMQ6TcNE5Ew==";
      };
    };
    "fast-json-patch-2.2.1" = {
      name = "fast-json-patch";
      packageName = "fast-json-patch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-patch/-/fast-json-patch-2.2.1.tgz";
        sha512 = "4j5uBaTnsYAV5ebkidvxiLUYOwjQ+JSFljeqfTxCrH9bDmlCQaOJFS84oDJ2rAXZq2yskmk3ORfoP9DCwqFNig==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fastq-1.13.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.13.0.tgz";
        sha512 = "YpkpUnK8od0o1hmeSc7UUs/eB/vIPWJYjKck2QKIzAf71Vm1AAQ3EbuZB3g2JIy+pg+ERD0vqI79KyZiB2e2Nw==";
      };
    };
    "fd-chunk-store-2.0.0" = {
      name = "fd-chunk-store";
      packageName = "fd-chunk-store";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-chunk-store/-/fd-chunk-store-2.0.0.tgz";
        sha1 = "32e1024cc85734707b12c54c0498fe4368869637";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.3" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.3.tgz";
        sha512 = "1lLKB2Mu3aGP1Q/2eCOx0fNbRMe7XdwktwOruhfqqd0rIJWwN4Dh+E3hrPSlDCXnSR7UtZ1N38rVXm+6+MEhJQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "glob-7.2.0" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.0.tgz";
        sha512 = "lmLf6gtyrPq8tTjSmrO94wBeQbFR3HbLHbuyD69wuyQkImp2hWqMGB47OX65FBkPffO641IP9jWa1z4ivqG26Q==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "glob-run-0.1.7" = {
      name = "glob-run";
      packageName = "glob-run";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-run/-/glob-run-0.1.7.tgz";
        sha512 = "8zLtPFAhK1kL6nghJfwDW5LEggkEXJxsq+bvTzwiluAjvGCIoyi3grpWs0dESSPqYOJ/184oIYqT3+szTqwyjw==";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.1.5" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.1.5.tgz";
        sha512 = "nmT2T0lljbxdQZfspsno9hgrG3Uir6Ks5afism62poxqBM6sDnMEuPmzTq8XN0OEwqKLLdh1jQI3qyE66Nzb3w==";
      };
    };
    "hash-base-3.1.0" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.1.0.tgz";
        sha512 = "1nmYp/rhMDiE7AYkDw+lLwlAzz0AntGIe51F3RfFfEqyQ3feY2eI/NcwC6umIQVOASPMsWJLJScWKSSvzL9IVA==";
      };
    };
    "hash.js-1.1.7" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.7.tgz";
        sha512 = "taOaskGt4z4SOANNseOviYDvjEJinIkRgmp7LbKP2YTTmVxWBl87s/uzK9r+44BclBSp2X7K1hqeNfz9JbBeXA==";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "http-errors-1.4.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.4.0.tgz";
        sha1 = "6c0242dea6b3df7afda153c71089b31c6e82aabf";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "ip-1.1.5" = {
      name = "ip";
      packageName = "ip";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.1.5.tgz";
        sha1 = "bdded70114290828c0a039e72ef25f5aaec4354a";
      };
    };
    "is-buffer-2.0.5" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.5.tgz";
        sha512 = "i2R6zNFDwgEHJyQUtJEk0XFi1i0dPFn/oqjK3/vPCcDeJvW5NQ83V8QbicfF1SupOaB0h8ntgBC2YiE7dfyctQ==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isomorphic-ws-4.0.1" = {
      name = "isomorphic-ws";
      packageName = "isomorphic-ws";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-ws/-/isomorphic-ws-4.0.1.tgz";
        sha512 = "BhBvN2MBpWTaSHdWRb/bwdZJ1WaehQ2L1KngkCkfLUGF0mAWAT1sQUQacEmQ0jXkFw/czDXPNQSL5u2/Krsz1w==";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "javascript-state-machine-3.1.0" = {
      name = "javascript-state-machine";
      packageName = "javascript-state-machine";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/javascript-state-machine/-/javascript-state-machine-3.1.0.tgz";
        sha512 = "BwhYxQ1OPenBPXC735RgfB+ZUG8H3kjsx8hrYTgWnoy6TPipEy4fiicyhT2lxRKAXq9pG7CfFT8a2HLr6Hmwxg==";
      };
    };
    "jayson-3.6.6" = {
      name = "jayson";
      packageName = "jayson";
      version = "3.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/jayson/-/jayson-3.6.6.tgz";
        sha512 = "f71uvrAWTtrwoww6MKcl9phQTC+56AopLyEenWvKVAIMz+q0oVGj6tenLZ7Z6UiPBkJtKLj4kt0tACllFQruGQ==";
      };
    };
    "js-beautify-1.14.0" = {
      name = "js-beautify";
      packageName = "js-beautify";
      version = "1.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-beautify/-/js-beautify-1.14.0.tgz";
        sha512 = "yuck9KirNSCAwyNJbqW+BxJqJ0NLJ4PwBUzQQACl5O3qHMBXVkXb/rD0ilh/Lat/tn88zSZ+CAHOlk0DsY7GuQ==";
      };
    };
    "js-sha256-0.9.0" = {
      name = "js-sha256";
      packageName = "js-sha256";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-sha256/-/js-sha256-0.9.0.tgz";
        sha512 = "sga3MHh9sgQN2+pJ9VYZ+1LPwXOxuBJBA5nrR5/ofPfuiJBE2hnjsaN8se8JznOmGLN2p49Pe5U/ttafcs/apA==";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-pointer-0.6.2" = {
      name = "json-pointer";
      packageName = "json-pointer";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-pointer/-/json-pointer-0.6.2.tgz";
        sha512 = "vLWcKbOaXlO+jvRy4qNd+TI1QUPZzfJj1tpJ3vAXDych5XJf93ftpUKe5pKCrzyIIwgBJcOcCVRUfqQP25afBw==";
      };
    };
    "json-schema-0.4.0" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.4.0.tgz";
        sha512 = "es94M3nTIfsEPisRafak+HDLfHXnKBhV3vU5eqPcS3flIWqcxJWgXHXiey3YrpaNsanY5ei1VoYEbOzijuq9BA==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "jsprim-1.4.2" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.2.tgz";
        sha512 = "P2bSOMAc/ciLz6DzgjVlGJP9+BrJWu5UDGK70C2iweC5QBIeFf0ZXRvGjEj2uYgrY2MkAAhsSWHDWlFtEroZWw==";
      };
    };
    "level-7.0.1" = {
      name = "level";
      packageName = "level";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/level/-/level-7.0.1.tgz";
        sha512 = "w3E64+ALx2eZf8RV5JL4kIcE0BFAvQscRYd1yU4YVqZN9RGTQxXSvH202xvK15yZwFFxRXe60f13LJjcJ//I4Q==";
      };
    };
    "level-codec-10.0.0" = {
      name = "level-codec";
      packageName = "level-codec";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/level-codec/-/level-codec-10.0.0.tgz";
        sha512 = "QW3VteVNAp6c/LuV6nDjg7XDXx9XHK4abmQarxZmlRSDyXYk20UdaJTSX6yzVvQ4i0JyWSB7jert0DsyD/kk6g==";
      };
    };
    "level-concat-iterator-3.1.0" = {
      name = "level-concat-iterator";
      packageName = "level-concat-iterator";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/level-concat-iterator/-/level-concat-iterator-3.1.0.tgz";
        sha512 = "BWRCMHBxbIqPxJ8vHOvKUsaO0v1sLYZtjN3K2iZJsRBYtp+ONsY6Jfi6hy9K3+zolgQRryhIn2NRZjZnWJ9NmQ==";
      };
    };
    "level-errors-3.0.1" = {
      name = "level-errors";
      packageName = "level-errors";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/level-errors/-/level-errors-3.0.1.tgz";
        sha512 = "tqTL2DxzPDzpwl0iV5+rBCv65HWbHp6eutluHNcVIftKZlQN//b6GEnZDM2CvGZvzGYMwyPtYppYnydBQd2SMQ==";
      };
    };
    "level-iterator-stream-5.0.0" = {
      name = "level-iterator-stream";
      packageName = "level-iterator-stream";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/level-iterator-stream/-/level-iterator-stream-5.0.0.tgz";
        sha512 = "wnb1+o+CVFUDdiSMR/ZymE2prPs3cjVLlXuDeSq9Zb8o032XrabGEXcTCsBxprAtseO3qvFeGzh6406z9sOTRA==";
      };
    };
    "level-js-6.1.0" = {
      name = "level-js";
      packageName = "level-js";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/level-js/-/level-js-6.1.0.tgz";
        sha512 = "i7mPtkZm68aewfv0FnIUWvFUFfoyzIvVKnUmuQGrelEkP72vSPTaA1SGneWWoCV5KZJG4wlzbJLp1WxVNGuc6A==";
      };
    };
    "level-packager-6.0.1" = {
      name = "level-packager";
      packageName = "level-packager";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/level-packager/-/level-packager-6.0.1.tgz";
        sha512 = "8Ezr0XM6hmAwqX9uu8IGzGNkWz/9doyPA8Oo9/D7qcMI6meJC+XhIbNYHukJhIn8OGdlzQs/JPcL9B8lA2F6EQ==";
      };
    };
    "level-supports-2.1.0" = {
      name = "level-supports";
      packageName = "level-supports";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/level-supports/-/level-supports-2.1.0.tgz";
        sha512 = "E486g1NCjW5cF78KGPrMDRBYzPuueMZ6VBXHT6gC7A8UYWGiM14fGgp+s/L1oFfDWSPV/+SFkYCmZ0SiESkRKA==";
      };
    };
    "leveldown-6.1.0" = {
      name = "leveldown";
      packageName = "leveldown";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/leveldown/-/leveldown-6.1.0.tgz";
        sha512 = "8C7oJDT44JXxh04aSSsfcMI8YiaGRhOFI9/pMEL7nWJLVsWajDPTRxsSHTM2WcTVY5nXM+SuRHzPPi0GbnDX+w==";
      };
    };
    "levelup-5.1.1" = {
      name = "levelup";
      packageName = "levelup";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/levelup/-/levelup-5.1.1.tgz";
        sha512 = "0mFCcHcEebOwsQuk00WJwjLI6oCjbBuEYdh/RaRqhjnyVlzqf41T1NnDtCedumZ56qyIh8euLFDqV1KfzTAVhg==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lru-cache-4.1.5" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.5.tgz";
        sha512 = "sWZlbEP2OsHNkXrMl5GYk/jKk70MBng6UU4YI/qGDYbgf6YbP4EvmqISbXCoJiRKs+1bSpFHVgQxvJ17F2li5g==";
      };
    };
    "ltgt-2.2.1" = {
      name = "ltgt";
      packageName = "ltgt";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ltgt/-/ltgt-2.2.1.tgz";
        sha1 = "f35ca91c493f7b73da0e07495304f17b31f87ee5";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "merkle-lib-2.0.10" = {
      name = "merkle-lib";
      packageName = "merkle-lib";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/merkle-lib/-/merkle-lib-2.0.10.tgz";
        sha1 = "82b8dbae75e27a7785388b73f9d7725d0f6f3326";
      };
    };
    "merkletreejs-0.1.11" = {
      name = "merkletreejs";
      packageName = "merkletreejs";
      version = "0.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/merkletreejs/-/merkletreejs-0.1.11.tgz";
        sha512 = "nJN3VIHeIAyB/PjO5Dj/Y0SEK7CGCCLD2IbV4el2kUIwlOtX3GOr5MwVO4EU+0AXvoDnJ0nmaLe5O86uIjWz/Q==";
      };
    };
    "micromatch-4.0.4" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.4.tgz";
        sha512 = "pRmzw/XUcwXGpD9aI9q/0XOwLNygjETJ8y0ao0wdqprrzDa4YnxLcz7fQRZr8voh8V10kGhABbNcHVk5wHgWwg==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minsc-0.2.0" = {
      name = "minsc";
      packageName = "minsc";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minsc/-/minsc-0.2.0.tgz";
        sha512 = "cvIke62kbnZQv59LS5d0R921bkcq3FVz2MmN4RsWnQrusozQpxh/wbOOR5JlrRtNFLkceIz470Dj+kflYjzgzQ==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "nan-2.14.2" = {
      name = "nan";
      packageName = "nan";
      version = "2.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.14.2.tgz";
        sha512 = "M2ufzIiINKCuDfBSAUr1vWQ+vuVcA9kqx8JJUsbQi6yf1uGRyb7HfpdfUr5qLXf3B/t8dPvcjhKMmlfnP47EzQ==";
      };
    };
    "napi-macros-2.0.0" = {
      name = "napi-macros";
      packageName = "napi-macros";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/napi-macros/-/napi-macros-2.0.0.tgz";
        sha512 = "A0xLykHtARfueITVDernsAWdtIMbOJgKgcluwENp3AlsKN/PloyO10HtmoqnFAQAcxPkgZN7wdfPfEd0zNGxbg==";
      };
    };
    "nat-upnp-1.1.1" = {
      name = "nat-upnp";
      packageName = "nat-upnp";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nat-upnp/-/nat-upnp-1.1.1.tgz";
        sha512 = "b1Q+sf9fHGCXhlWErNgTTEto8A02MnNysw3vx3kD1657+/Ae23vPEAB6QBh+9RqLL4+xw/LmjVTiLy6A7Cx0xw==";
      };
    };
    "node-gyp-build-4.3.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.3.0.tgz";
        sha512 = "iWjXZvmboq0ja1pUGULQBexmxq8CV4xBhX7VDOTbL7ZR4FOowwY/VOtRxBN/yKxmdGoIp4j5ysNT4u3S2pDQ3Q==";
      };
    };
    "nopt-5.0.0" = {
      name = "nopt";
      packageName = "nopt";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-5.0.0.tgz";
        sha512 = "Tbj67rffqceeLpcRXrT7vKAN8CwfPeIBgM7E6iBkmKLV7bEMwpGgYLGv0jACUsECaa/vuxP0IjEont6umdMgtQ==";
      };
    };
    "oauth-sign-0.9.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.9.0.tgz";
        sha512 = "fexhUFFPTGV8ybAtSIGbV6gOkSv8UtRbDBnAyLQw4QPKkgNlsH2ByPGtMUqdWkos6YCRmAqViwgZrJc/mRDzZQ==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "p-event-4.2.0" = {
      name = "p-event";
      packageName = "p-event";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-event/-/p-event-4.2.0.tgz";
        sha512 = "KXatOjCRXXkSePPb1Nbi0p0m+gQAwdlbhi4wQKJPI1HsMQS9g+Sqp2o+QHziPr7eYJyOZet836KoHEVM1mwOrQ==";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "3fbcfb15b899a44123b34b6dcc18b724336a2cae";
      };
    };
    "p-timeout-3.2.0" = {
      name = "p-timeout";
      packageName = "p-timeout";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-timeout/-/p-timeout-3.2.0.tgz";
        sha512 = "rhIwUycgwwKcP9yTOOFK/AKsAopjjCakVqLHePO3CC6Mir1Z99xT+R63jZxAT5lFZLa2inS5h+ZS2GvR99/FBg==";
      };
    };
    "path-browserify-1.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-1.0.1.tgz";
        sha512 = "b7uo2UCUOYZcnF/3ID0lulOJi/bafxa1xPe7ZPsammBSpjSWQkjNxlt635YGS2MiR9GjvuXCtz2emr3jbsz98g==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-match-1.2.4" = {
      name = "path-match";
      packageName = "path-match";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-match/-/path-match-1.2.4.tgz";
        sha1 = "a62747f3c7e0c2514762697f24443585b09100ea";
      };
    };
    "path-to-regexp-1.8.0" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-1.8.0.tgz";
        sha512 = "n43JRhlUKUAlibEJhPeir1ncUID16QnEjNpwzNdO3Lm4ywrBpBZ5oLD0I6br9evr1Y9JTqwRtAh7JLoOzAQdVA==";
      };
    };
    "pbkdf2-3.1.2" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.1.2.tgz";
        sha512 = "iuh7L6jA7JEGu2WxDwtQP1ddOpaJNC4KlDEFfdQajSGgGPNi4OyDc2R7QnbY2bR9QjBVGwgvTdNJZoE7RaxUMA==";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pluralize-8.0.0" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-8.0.0.tgz";
        sha512 = "Nc3IT5yHzflTfbjgqWcCPpo7DaKy4FnpB0l/zCAW0Tc7jxAiuqSxHasntB3D7887LSrA93kDJ9IXovxJYxyLCA==";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "psl-1.8.0" = {
      name = "psl";
      packageName = "psl";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/psl/-/psl-1.8.0.tgz";
        sha512 = "RIdOzyoavK+hA18OGGWDqUTsCLhtA7IcZ/6NCs4fFJaHBDab+pDDmDIByWFRQJq2Cd7r1OoQxBGKOaztq+hjIQ==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "qs-6.5.3" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.3.tgz";
        sha512 = "qxXIEh4pCGfHICj1mAJQ2/2XVZkjCDTcEgfoSQxc/fYivUZxTkk7L3bDBJSoNrEzXI17oUO5Dp07ktqE5KzczA==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "redis-3.1.2" = {
      name = "redis";
      packageName = "redis";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-3.1.2.tgz";
        sha512 = "grn5KoZLr/qrRQVwoSkmzdbw6pwF+/rwODtrOr6vuBRiR/f3rjSTGupbF90Zpqm2oenix8Do6RV7pYEkGwlKkw==";
      };
    };
    "redis-commands-1.7.0" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.7.0.tgz";
        sha512 = "nJWqw3bTFy21hX/CPKHth6sfhZbdiHP6bTawSgQBlKOVRG7EZkfHbbHwQJnrE4vsQf0CMNE+3gJ4Fmm16vdVlQ==";
      };
    };
    "redis-errors-1.2.0" = {
      name = "redis-errors";
      packageName = "redis-errors";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-errors/-/redis-errors-1.2.0.tgz";
        sha1 = "eb62d2adb15e4eaf4610c04afe1529384250abad";
      };
    };
    "redis-parser-3.0.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-3.0.0.tgz";
        sha1 = "b66d828cdcafe6b4b8a428a7def4c6bcac31c8b4";
      };
    };
    "request-2.88.2" = {
      name = "request";
      packageName = "request";
      version = "2.88.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.88.2.tgz";
        sha512 = "MsvtOrfG9ZcrOwAW+Qi+F6HbD0CWXEh9ou77uOb7FM2WPhwT7smM833PzanhJLsgXjN89Ir6V2PczXNnMpwKhw==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rimraf-2.7.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz";
        sha512 = "uWjbaKIK3T1OSVptzX7Nl6PvQ3qAGtKEtVRjRuazjfL3Bx5eI409VZSqgND+4UNnmzLVdPj9FqFJNPqBZFve4w==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "run-parallel-limit-1.1.0" = {
      name = "run-parallel-limit";
      packageName = "run-parallel-limit";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel-limit/-/run-parallel-limit-1.1.0.tgz";
        sha512 = "jJA7irRNM91jaKc3Hcl1npHsFLOXOoTkPCUL1JEa1R82O2miplXXRaGdjW/KM/98YQWDhJLiSs793CnXfblJUw==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "sigmund-1.0.1" = {
      name = "sigmund";
      packageName = "sigmund";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz";
        sha1 = "3ff21f198cad2175f9f3b781853fd94d0d19b590";
      };
    };
    "simple-aes-0.1.1" = {
      name = "simple-aes";
      packageName = "simple-aes";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-aes/-/simple-aes-0.1.1.tgz";
        sha512 = "R4Dqz3TlzCyG3qkunLvYWC/gToWvOBqyR9EHIAQQZq2KOnybprjt2zcrWi1DZOyEH9QGLbDl9hqk4TTsxwLIqw==";
      };
    };
    "sshpk-1.17.0" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.17.0.tgz";
        sha512 = "/9HIEs1ZXGhSPE8X6Ccm7Nam1z8KcoCqPdI7ecm1N33EzAetWahvQWVqLZtaZQ+IDKX4IyA2o0gBzqIMkAagHQ==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "struct-0.0.12" = {
      name = "struct";
      packageName = "struct";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/struct/-/struct-0.0.12.tgz";
        sha1 = "8330af872664e9a5bd678664524857c50908038a";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "tiny-secp256k1-2.2.1" = {
      name = "tiny-secp256k1";
      packageName = "tiny-secp256k1";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-secp256k1/-/tiny-secp256k1-2.2.1.tgz";
        sha512 = "/U4xfVqnVxJXN4YVsru0E6t5wVncu2uunB8+RVR40fYUxkKYUPS10f+ePQZgFBoE/Jbf9H1NBveupF2VmB58Ng==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tough-cookie-2.5.0" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.5.0.tgz";
        sha512 = "nlLsUzgm1kfLXSXfRZMc1KLAugd4hqJHDTvc2hDIwS3mZAfMEuMbc03SujMF+GEcpaX/qboeycw6iO8JwVv2+g==";
      };
    };
    "treeify-1.1.0" = {
      name = "treeify";
      packageName = "treeify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/treeify/-/treeify-1.1.0.tgz";
        sha512 = "1m4RA7xVAJrSGrrXGs0L3YTwyvBs2S8PbRHaLZAkFw7JR8oIFwYtysxlBZhYIa7xSyiYJKZ3iGrrk55cGA3i9A==";
      };
    };
    "ts-morph-10.1.0" = {
      name = "ts-morph";
      packageName = "ts-morph";
      version = "10.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-morph/-/ts-morph-10.1.0.tgz";
        sha512 = "hfskRPAbc+N1+2QvPLvJ0MOrhcwxJuBlCbX+D+9T7UnrZZqsdbmWb6FfywQ7sghyqwok6Pc8ZPwzaumlOJ8OBA==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "typeforce-1.18.0" = {
      name = "typeforce";
      packageName = "typeforce";
      version = "1.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typeforce/-/typeforce-1.18.0.tgz";
        sha512 = "7uc1O8h1M1g0rArakJdf0uLRSSgFcYexrVoKo+bzJd32gd4gDy2L/Z+8/FjPnU9ydY3pEnVPtr9FyscYY60K1g==";
      };
    };
    "uint8array-tools-0.0.7" = {
      name = "uint8array-tools";
      packageName = "uint8array-tools";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/uint8array-tools/-/uint8array-tools-0.0.7.tgz";
        sha512 = "vrrNZJiusLWoFWBqz5Y5KMCgP9W9hnjZHzZiZRT8oNAkq3d5Z5Oe76jAvVVSRh4U8GGR90N2X1dWtrhvx6L8UQ==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "uuid-8.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz";
        sha512 = "+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg==";
      };
    };
    "varuint-bitcoin-1.1.2" = {
      name = "varuint-bitcoin";
      packageName = "varuint-bitcoin";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/varuint-bitcoin/-/varuint-bitcoin-1.1.2.tgz";
        sha512 = "4EVb+w4rx+YfVM32HQX42AbbT7/1f5zwAYhIujKXKk8NQK+JfRVl3pqT3hjNn/L+RstigmGGKVwHA/P0wgITZw==";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "wif-2.0.6" = {
      name = "wif";
      packageName = "wif";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/wif/-/wif-2.0.6.tgz";
        sha1 = "08d3f52056c66679299726fade0d432ae74b4704";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.5.7" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.7.tgz";
        sha512 = "KMvVuFzpKBuiIXW3E4u3mySRO2/mCHSyZDJQM5NQ9Q9KHWHWh0NHgfbRMLLrceUK5qAL4ytALJbpRMjixFZh8A==";
      };
    };
    "xml2js-0.1.14" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.1.14.tgz";
        sha1 = "5274e67f5a64c5f92974cd85139e0332adc6b90c";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "zeromq-5.2.8" = {
      name = "zeromq";
      packageName = "zeromq";
      version = "5.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/zeromq/-/zeromq-5.2.8.tgz";
        sha512 = "bXzsk7KOmgLSv1tC0Ms1VXBy90+Rz27ZYf27cLuldRYbpqYpuWJfxxHFhO710t22zgWBnmdUP0m3SKFpLI0u5g==";
      };
    };
  };
  args = {
    name = "_at_fabric_slash_core";
    packageName = "@fabric/core";
    version = "0.1.0-dev";
    src = nix-gitignore.gitignoreSourcePure [ ".git" ../../.gitignore ] ../..;
    dependencies = [
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@ts-morph/common-0.9.2"
      sources."@types/connect-3.4.35"
      sources."@types/express-serve-static-core-4.17.28"
      sources."@types/lodash-4.14.180"
      sources."@types/node-11.11.6"
      sources."@types/qs-6.9.7"
      sources."@types/range-parser-1.2.4"
      sources."@types/ws-7.4.7"
      sources."@webassemblyjs/ast-1.11.1"
      sources."@webassemblyjs/floating-point-hex-parser-1.11.1"
      sources."@webassemblyjs/helper-api-error-1.11.1"
      sources."@webassemblyjs/helper-numbers-1.11.1"
      sources."@webassemblyjs/helper-wasm-bytecode-1.11.1"
      sources."@xtuc/long-4.2.2"
      sources."JSONStream-1.3.5"
      sources."abbrev-1.1.1"
      sources."abstract-leveldown-7.2.0"
      (sources."ajv-6.12.6" // {
        dependencies = [
          sources."fast-deep-equal-3.1.3"
        ];
      })
      sources."arbitrary-1.4.10"
      sources."asn1-0.2.6"
      sources."assert-plus-1.0.0"
      sources."async-3.2.3"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.11.0"
      sources."balanced-match-1.0.2"
      sources."base-x-1.1.0"
      sources."base58check-2.0.0"
      sources."base64-js-1.5.1"
      sources."bcoin-git+https://github.com/bcoin-org/bcoin#acdeb84767f3ceb82b4a75931fe353229c3bc7b5"
      sources."bcrypt-pbkdf-1.0.2"
      sources."bech32-2.0.0"
      sources."bigi-1.4.2"
      sources."bip-schnorr-0.6.6"
      sources."bip174-2.0.1"
      (sources."bip32-3.0.1" // {
        dependencies = [
          sources."@types/node-10.12.18"
        ];
      })
      sources."bip39-3.0.4"
      sources."bip65-1.0.3"
      sources."bip68-1.0.4"
      sources."bitcoinjs-lib-6.0.1"
      sources."blessed-0.1.81"
      sources."bn.js-4.12.0"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."brorand-1.1.0"
      sources."bs58-3.1.0"
      (sources."bs58check-2.1.2" // {
        dependencies = [
          sources."base-x-3.0.9"
          sources."bs58-4.0.1"
        ];
      })
      sources."buffer-6.0.3"
      sources."buffer-reverse-1.0.1"
      sources."caseless-0.12.0"
      sources."catering-2.1.1"
      sources."cipher-base-1.0.4"
      sources."clightningjs-0.2.2"
      sources."code-block-writer-10.1.1"
      sources."combined-stream-1.0.8"
      sources."commander-6.2.1"
      sources."concat-map-0.0.1"
      sources."config-chain-1.1.13"
      sources."content-type-1.0.4"
      sources."core-util-is-1.0.2"
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."crypto-js-3.3.0"
      sources."dashdash-1.14.1"
      sources."deferred-leveldown-7.0.0"
      sources."defined-1.0.0"
      sources."delay-5.0.0"
      sources."delayed-stream-1.0.0"
      sources."denque-1.5.1"
      sources."dotparser-0.3.0"
      sources."ecc-jsbn-0.1.2"
      sources."ecpair-2.0.1"
      sources."ecurve-1.0.6"
      (sources."editorconfig-0.15.3" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."elliptic-6.5.4"
      sources."encoding-down-7.1.0"
      sources."es6-promise-4.2.8"
      sources."es6-promisify-5.0.0"
      sources."extend-3.0.2"
      sources."extsprintf-1.3.0"
      sources."eyes-0.1.8"
      sources."fast-deep-equal-2.0.1"
      sources."fast-glob-3.2.11"
      sources."fast-json-patch-2.2.1"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fastq-1.13.0"
      sources."fd-chunk-store-2.0.0"
      sources."fill-range-7.0.1"
      sources."foreach-2.0.5"
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.3"
      sources."fs.realpath-1.0.0"
      sources."getpass-0.1.7"
      sources."glob-7.2.0"
      sources."glob-parent-5.1.2"
      sources."glob-run-0.1.7"
      sources."har-schema-2.0.0"
      sources."har-validator-5.1.5"
      sources."hash-base-3.1.0"
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      (sources."http-errors-1.4.0" // {
        dependencies = [
          sources."inherits-2.0.1"
        ];
      })
      sources."http-signature-1.2.0"
      sources."ieee754-1.2.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."ip-1.1.5"
      sources."is-buffer-2.0.5"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."is-typedarray-1.0.0"
      sources."isarray-0.0.1"
      sources."isomorphic-ws-4.0.1"
      sources."isstream-0.1.2"
      sources."javascript-state-machine-3.1.0"
      (sources."jayson-3.6.6" // {
        dependencies = [
          sources."@types/node-12.20.47"
          sources."commander-2.20.3"
        ];
      })
      sources."js-beautify-1.14.0"
      sources."js-sha256-0.9.0"
      sources."jsbn-0.1.1"
      sources."json-pointer-0.6.2"
      sources."json-schema-0.4.0"
      sources."json-schema-traverse-0.4.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsonparse-1.3.1"
      sources."jsprim-1.4.2"
      sources."level-7.0.1"
      sources."level-codec-10.0.0"
      sources."level-concat-iterator-3.1.0"
      sources."level-errors-3.0.1"
      sources."level-iterator-stream-5.0.0"
      sources."level-js-6.1.0"
      sources."level-packager-6.0.1"
      sources."level-supports-2.1.0"
      sources."leveldown-6.1.0"
      sources."levelup-5.1.1"
      sources."lodash-4.17.21"
      sources."lodash.merge-4.6.2"
      sources."lru-cache-4.1.5"
      sources."ltgt-2.2.1"
      sources."md5.js-1.3.5"
      sources."merge2-1.4.1"
      sources."merkle-lib-2.0.10"
      sources."merkletreejs-0.1.11"
      sources."micromatch-4.0.4"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."minimatch-3.1.2"
      sources."minsc-0.2.0"
      sources."mkdirp-1.0.4"
      sources."nan-2.14.2"
      sources."napi-macros-2.0.0"
      (sources."nat-upnp-1.1.1" // {
        dependencies = [
          sources."async-2.6.3"
        ];
      })
      sources."node-gyp-build-4.3.0"
      sources."nopt-5.0.0"
      sources."oauth-sign-0.9.0"
      sources."once-1.4.0"
      sources."p-event-4.2.0"
      sources."p-finally-1.0.0"
      sources."p-timeout-3.2.0"
      sources."path-browserify-1.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-match-1.2.4"
      sources."path-to-regexp-1.8.0"
      sources."pbkdf2-3.1.2"
      sources."performance-now-2.1.0"
      sources."picomatch-2.3.1"
      sources."pluralize-8.0.0"
      sources."proto-list-1.2.4"
      sources."pseudomap-1.0.2"
      sources."psl-1.8.0"
      sources."punycode-2.1.1"
      sources."qs-6.5.3"
      sources."queue-microtask-1.2.3"
      sources."randombytes-2.1.0"
      sources."readable-stream-3.6.0"
      sources."redis-3.1.2"
      sources."redis-commands-1.7.0"
      sources."redis-errors-1.2.0"
      sources."redis-parser-3.0.0"
      (sources."request-2.88.2" // {
        dependencies = [
          sources."uuid-3.4.0"
        ];
      })
      sources."reusify-1.0.4"
      sources."rimraf-2.7.1"
      sources."ripemd160-2.0.2"
      sources."run-parallel-1.2.0"
      sources."run-parallel-limit-1.1.0"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."semver-5.7.1"
      sources."sha.js-2.4.11"
      sources."sigmund-1.0.1"
      sources."simple-aes-0.1.1"
      sources."sshpk-1.17.0"
      sources."statuses-1.5.0"
      sources."string_decoder-1.3.0"
      sources."struct-0.0.12"
      sources."through-2.3.8"
      sources."tiny-secp256k1-2.2.1"
      sources."to-regex-range-5.0.1"
      sources."tough-cookie-2.5.0"
      sources."treeify-1.1.0"
      sources."ts-morph-10.1.0"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."typeforce-1.18.0"
      sources."uint8array-tools-0.0.7"
      sources."uri-js-4.4.1"
      sources."util-deprecate-1.0.2"
      sources."uuid-8.3.2"
      sources."varuint-bitcoin-1.1.2"
      sources."verror-1.10.0"
      sources."wif-2.0.6"
      sources."wrappy-1.0.2"
      sources."ws-7.5.7"
      sources."xml2js-0.1.14"
      sources."yallist-2.1.2"
      sources."zeromq-5.2.8"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "experimental p2p framework";
      homepage = "https://github.com/FabricLabs/fabric#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
